name: Provisioning

on: 
  workflow_dispatch

jobs:
  manual_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create S3 Bucket
        run: | 
          aws s3api create-bucket --bucket delete-my-bucket --region eu-west-2 --create-bucket-configuration LocationConstraint=eu-west-2
      
      - name: Configure Web hosting 
        run: |
          aws s3 website s3://delete-my-bucket/ --index-document index.html --error-document index.html
      - name: Configure access control
        run: |
          aws s3api put-public-access-block --bucket delete-my-bucket --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
      - name: Put S3 Policy
        run: |
          aws s3api put-bucket-policy --bucket delete-my-bucket --policy file://policy.json

token df22fa7072cfeb31edfa444a92baaa06c7e15f74 


curl --request POST \
  --url https://github.com/codurance/all-aboard-frontend/dispatches \
  --header 'Accept: application/vnd.github.everest-preview+json' \
  --header 'Authorization: Bearer 38751698388cc245f48a3a640d5f60f9b66b899d' \
  --header 'Content-Type: application/json' \
  --data '{"event_type": "destroy"}'
